import { DifficultyLevel, StageDefinition } from "../../../shared/game";

type DifficultyStageMap = Record<DifficultyLevel, StageDefinition[]>;

export const stagesByDifficulty: DifficultyStageMap = {
  explorador: [
    {
      id: "e1",
      title: "Sirena de altura",
      prompt: "Amanda pierde apoyo. ¿Qué señal muestra que está a punto de caer?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Sus dedos resbalan", "Se rompe la terraza", "Se apagan las luces", "Llega un guardia"],
      answer: "SUS DEDOS RESBALAN",
      explanation: "La amenaza inmediata es perder el agarre.",
    },
    {
      id: "e2",
      title: "Secuencia de rescate",
      prompt: "Toca la secuencia en el orden correcto.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Sigue"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Sigue"],
      memoryRevealMs: 4500,
      answer: "RESBALA, DRON, APOYO, SIGUE",
      explanation: "Así se recompone el rescate de Benson.",
    },
    {
      id: "e3",
      title: "Escondite",
      prompt: "El guardia se acerca. ¿Dónde debe esconderse Amanda?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Jardineras", "Mesa de cristal", "Ventana", "Barandilla"],
      answer: "JARDINERAS",
      explanation: "Las jardineras son la única cobertura real.",
    },
    {
      id: "e4",
      title: "Último empuje",
      prompt: "Ordena los pasos para llegar al despacho.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Izquierda", "Sube", "Terraza", "Escóndete"],
      answer: "IZQUIERDA, SUBE, TERRAZA, ESCONDETE",
      explanation: "Esa es la ruta limpia marcada por Eric.",
    },
  ],
  agente: [
    {
      id: "a1",
      title: "Pánico controlado",
      prompt: "¿Qué necesita Amanda para salir viva de la terraza?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Pensar con frialdad", "Saltar sin mirar", "Esperar quieta", "Romper el cristal"],
      answer: "PENSAR CON FRIALDAD",
      explanation: "El control mental es su mejor arma.",
    },
    {
      id: "a2",
      title: "Ruta del dron",
      prompt: "Toca la secuencia exacta del rescate aéreo.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Respira", "Sube"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Respira", "Sube"],
      memoryRevealMs: 4200,
      answer: "RESBALA, DRON, APOYO, RESPIRA, SUBE",
      explanation: "El apoyo del dron le devuelve el control y luego sigue subiendo.",
    },
    {
      id: "a3",
      title: "Señal rota",
      prompt: "Se corta la voz. ¿Qué hace Eric para salvar la misión?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Confía en Esme", "Abandona la sala", "Llama a Benson", "Apaga el sistema"],
      answer: "CONFIA EN ESME",
      explanation: "Eric se arriesga y convierte a Esme en aliada.",
    },
    {
      id: "a4",
      title: "Código de movimiento",
      prompt: "Ordena las instrucciones de Eric.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Izquierda", "Diez metros", "Sube", "Terraza", "Cúbrete"],
      answer: "IZQUIERDA, DIEZ METROS, SUBE, TERRAZA, CUBRETE",
      explanation: "Es la cadena que lleva a Amanda hasta la terraza y la salva del guardia.",
    },
    {
      id: "a5",
      title: "Visión del guardia",
      prompt: "¿Qué advierte Eric justo antes de la cristalera?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Un guardia se acerca", "Benson perdió el dron", "Esme salió corriendo", "La llave aparece"],
      answer: "UN GUARDIA SE ACERCA",
      explanation: "Ese aviso dispara la maniobra de escondite.",
    },
    {
      id: "a6",
      title: "Entrada limpia",
      prompt: "Toca los pasos finales para sobrevivir.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Jardineras", "Quieta", "Guardia pasa", "Avanza"],
      answer: "JARDINERAS, QUIETA, GUARDIA PASA, AVANZA",
      explanation: "Amanda se esconde, aguanta, espera el paso del guardia y luego avanza.",
    },
  ],
  leyenda: [
    {
      id: "l1",
      title: "Lectura del vacío",
      prompt: "¿Qué indica que Amanda está al borde del desastre?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: ["Sus dedos patinan", "La música se detiene", "Esme grita", "Se cierra una puerta"],
      answer: "SUS DEDOS PATINAN",
      explanation: "La primera alarma es física: pierde el agarre.",
    },
    {
      id: "l2",
      title: "Cadena de vida",
      prompt: "Toca la secuencia exacta del rescate de Benson.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Agarre", "Respira", "Sube"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Agarre", "Respira", "Sube"],
      memoryRevealMs: 4000,
      answer: "RESBALA, DRON, APOYO, AGARRE, RESPIRA, SUBE",
      explanation: "La leyenda exige recordar cada paso del rescate.",
    },
    {
      id: "l3",
      title: "Aliada bajo presión",
      prompt: "¿Por qué Esme se vuelve la última esperanza de Eric?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: [
        "Porque necesita llegar al piso correcto a tiempo",
        "Porque conoce el código del banco",
        "Porque dirige a los guardias",
        "Porque controla la fiesta",
      ],
      answer: "PORQUE NECESITA LLEGAR AL PISO CORRECTO A TIEMPO",
      explanation: "Sin esa ayuda, la guía final se rompe.",
    },
    {
      id: "l4",
      title: "Ruta maestra",
      prompt: "Ordena la ruta completa de Eric.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Izquierda", "Diez metros", "Sube", "Último piso", "Terraza", "Escóndete"],
      answer: "IZQUIERDA, DIEZ METROS, SUBE, ULTIMO PISO, TERRAZA, ESCONDETE",
      explanation: "La ruta de leyenda incluye el tramo completo hasta la terraza.",
    },
    {
      id: "l5",
      title: "Muebles trampa",
      prompt: "¿Qué vuelve inútiles casi todos los escondites de la terraza?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: [
        "El mobiliario es transparente",
        "Todo está mojado",
        "Hay cámaras en el techo",
        "La terraza es pequeña",
      ],
      answer: "EL MOBILIARIO ES TRANSPARENTE",
      explanation: "Amanda lo entiende de golpe: casi no hay dónde ocultarse.",
    },
    {
      id: "l6",
      title: "Secuencia de sangre fría",
      prompt: "Toca la secuencia para no ser vista.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Jardineras", "Encogerse", "Esperar", "Guardia pasa", "Despacho"],
      answer: "JARDINERAS, ENCOGERSE, ESPERAR, GUARDIA PASA, DESPACHO",
      explanation: "La clave es esconderse, hacerse pequeña, esperar y moverse en el hueco justo.",
    },
    {
      id: "l7",
      title: "Golpe final",
      prompt: "¿Qué logra Amanda al final del tramo guiado?",
      inputLabel: "Elige",
      answerKind: "single-choice",
      options: [
        "Entrar en la terraza del despacho de Irma Dagon",
        "Huir de la torre",
        "Encontrar la llave en el ascensor",
        "Apagar los drones",
      ],
      answer: "ENTRAR EN LA TERRAZA DEL DESPACHO DE IRMA DAGON",
      explanation: "Ese es el cierre perfecto del recorrido.",
    },
    {
      id: "l8",
      title: "Huella de leyenda",
      prompt: "Ordena el recorrido completo del capítulo como si fueras el director de la misión.",
      inputLabel: "Orden",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Esme", "Ruta", "Jardineras", "Despacho"],
      answer: "RESBALA, DRON, ESME, RUTA, JARDINERAS, DESPACHO",
      explanation: "La versión leyenda pide unir rescate, apoyo, guía y entrada final en una sola cadena.",
    },
  ],
};
