import { DifficultyLevel, StageDefinition } from "../../../shared/game";

type DifficultyStageMap = Record<DifficultyLevel, StageDefinition[]>;

export const stagesByDifficulty: DifficultyStageMap = {
  explorador: [
    {
      id: "e1",
      title: "Radar rojo",
      prompt: "Escanea la fachada y marca la alerta real.",
      inputLabel: "Activa una alerta",
      mode: "radar",
      hint: "Busca el peligro que corta el ritmo de Amanda.",
      answerKind: "single-choice",
      options: ["Sus dedos resbalan", "Se rompe la terraza", "Se apagan las luces", "Llega un guardia"],
      answer: "SUS DEDOS RESBALAN",
      explanation: "La amenaza inmediata es perder el agarre.",
    },
    {
      id: "e2",
      title: "Eco de memoria",
      prompt: "Mira la cadena del rescate y reprodúcela antes de que se apague.",
      inputLabel: "Repite la cadena",
      mode: "memory",
      hint: "Obsérvala, espera y reconstruye el orden.",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Sigue"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Sigue"],
      memoryRevealMs: 4500,
      answer: "RESBALA, DRON, APOYO, SIGUE",
      explanation: "Así se recompone el rescate de Benson.",
    },
    {
      id: "e3",
      title: "Ruta sombra",
      prompt: "El guardia gira la cabeza. Elige el escondite que mantiene viva la misión.",
      inputLabel: "Marca la cobertura",
      mode: "route",
      hint: "Solo un punto de la terraza la cubre de verdad.",
      answerKind: "single-choice",
      options: ["Jardineras", "Mesa de cristal", "Ventana", "Barandilla"],
      answer: "JARDINERAS",
      explanation: "Las jardineras son la única cobertura real.",
    },
    {
      id: "e4",
      title: "Ruta turbo",
      prompt: "Traza la línea exacta para entrar al despacho sin perder velocidad.",
      inputLabel: "Traza la ruta",
      mode: "route",
      hint: "Une los movimientos de Eric en una sola corrida.",
      answerKind: "sequence",
      options: ["Izquierda", "Sube", "Terraza", "Escóndete"],
      answer: "IZQUIERDA, SUBE, TERRAZA, ESCONDETE",
      explanation: "Esa es la ruta limpia marcada por Eric.",
    },
  ],
  agente: [
    {
      id: "a1",
      title: "Pulso firme",
      prompt: "La torre vibra. Activa la decisión que mantiene el control.",
      inputLabel: "Pulsa la mejor jugada",
      mode: "signal",
      hint: "La mente fría puntúa más que el impulso.",
      answerKind: "single-choice",
      options: ["Pensar con frialdad", "Saltar sin mirar", "Esperar quieta", "Romper el cristal"],
      answer: "PENSAR CON FRIALDAD",
      explanation: "El control mental es su mejor arma.",
    },
    {
      id: "a2",
      title: "Combo dron",
      prompt: "Mira la cadena del rescate y lanzala en el mismo orden.",
      inputLabel: "Encadena la jugada",
      mode: "memory",
      hint: "Cuanto más limpio el orden, más sólido el rescate.",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Respira", "Sube"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Respira", "Sube"],
      memoryRevealMs: 4200,
      answer: "RESBALA, DRON, APOYO, RESPIRA, SUBE",
      explanation: "El apoyo del dron le devuelve el control y luego sigue subiendo.",
    },
    {
      id: "a3",
      title: "Canal secreto",
      prompt: "La señal cae. Elige la maniobra que revive la misión.",
      inputLabel: "Reabre la señal",
      mode: "radar",
      hint: "Eric no huye: busca una aliada.",
      answerKind: "single-choice",
      options: ["Confía en Esme", "Abandona la sala", "Llama a Benson", "Apaga el sistema"],
      answer: "CONFIA EN ESME",
      explanation: "Eric se arriesga y convierte a Esme en aliada.",
    },
    {
      id: "a4",
      title: "Carril oculto",
      prompt: "Construye la ruta exacta antes de que el guardia alcance la cristalera.",
      inputLabel: "Monta la ruta",
      mode: "route",
      hint: "Cada tramo importa; no hay hueco para piezas extra.",
      answerKind: "sequence",
      options: ["Izquierda", "Diez metros", "Sube", "Terraza", "Cúbrete"],
      answer: "IZQUIERDA, DIEZ METROS, SUBE, TERRAZA, CUBRETE",
      explanation: "Es la cadena que lleva a Amanda hasta la terraza y la salva del guardia.",
    },
    {
      id: "a5",
      title: "Alarma visual",
      prompt: "Detecta primero lo que Eric ve antes de que sea tarde.",
      inputLabel: "Marca la amenaza",
      mode: "signal",
      hint: "El peligro no es el dron: es quien se acerca.",
      answerKind: "single-choice",
      options: ["Un guardia se acerca", "Benson perdió el dron", "Esme salió corriendo", "La llave aparece"],
      answer: "UN GUARDIA SE ACERCA",
      explanation: "Ese aviso dispara la maniobra de escondite.",
    },
    {
      id: "a6",
      title: "Esprint final",
      prompt: "Amanda ya está casi dentro. Ejecuta el cierre sin romper el ritmo.",
      inputLabel: "Cierra la jugada",
      mode: "route",
      hint: "Esconderse, esperar y moverse en el hueco justo.",
      answerKind: "sequence",
      options: ["Jardineras", "Quieta", "Guardia pasa", "Avanza"],
      answer: "JARDINERAS, QUIETA, GUARDIA PASA, AVANZA",
      explanation: "Amanda se esconde, aguanta, espera el paso del guardia y luego avanza.",
    },
  ],
  leyenda: [
    {
      id: "l1",
      title: "Radar omega",
      prompt: "En modo leyenda, marca el detalle que rompe la estabilidad.",
      inputLabel: "Fija el objetivo",
      mode: "radar",
      hint: "El error empieza en las manos, no en el entorno.",
      answerKind: "single-choice",
      options: ["Sus dedos patinan", "La música se detiene", "Esme grita", "Se cierra una puerta"],
      answer: "SUS DEDOS PATINAN",
      explanation: "La primera alarma es física: pierde el agarre.",
    },
    {
      id: "l2",
      title: "Cadena perfecta",
      prompt: "Mira el rescate completo y lanzalo como una cadena limpia.",
      inputLabel: "Clava la secuencia",
      mode: "memory",
      hint: "No sobra ningún paso en esta dificultad.",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Apoyo", "Agarre", "Respira", "Sube"],
      memorySequence: ["Resbala", "Dron", "Apoyo", "Agarre", "Respira", "Sube"],
      memoryRevealMs: 4000,
      answer: "RESBALA, DRON, APOYO, AGARRE, RESPIRA, SUBE",
      explanation: "La leyenda exige recordar cada paso del rescate.",
    },
    {
      id: "l3",
      title: "Señal fantasma",
      prompt: "Elige por qué Esme se convierte en la pieza que salva toda la línea.",
      inputLabel: "Recupera la línea",
      mode: "signal",
      hint: "Sin esa ayuda, Eric no alcanza a guiar la parte final.",
      answerKind: "single-choice",
      options: [
        "Porque necesita llegar al piso correcto a tiempo",
        "Porque conoce el código del banco",
        "Porque dirige a los guardias",
        "Porque controla la fiesta",
      ],
      answer: "PORQUE NECESITA LLEGAR AL PISO CORRECTO A TIEMPO",
      explanation: "Sin esa ayuda, la guía final se rompe.",
    },
    {
      id: "l4",
      title: "Mapa maestro",
      prompt: "Traza la ruta completa como si llevaras el mando del operativo.",
      inputLabel: "Dibuja el mapa",
      mode: "route",
      hint: "Debe quedar exacta desde el giro inicial hasta la cobertura.",
      answerKind: "sequence",
      options: ["Izquierda", "Diez metros", "Sube", "Último piso", "Terraza", "Escóndete"],
      answer: "IZQUIERDA, DIEZ METROS, SUBE, ULTIMO PISO, TERRAZA, ESCONDETE",
      explanation: "La ruta de leyenda incluye el tramo completo hasta la terraza.",
    },
    {
      id: "l5",
      title: "Falso refugio",
      prompt: "Lee la terraza y detecta qué vuelve casi inútil cualquier escondite.",
      inputLabel: "Anula la trampa",
      mode: "radar",
      hint: "El problema no es tamaño ni humedad; es visibilidad.",
      answerKind: "single-choice",
      options: [
        "El mobiliario es transparente",
        "Todo está mojado",
        "Hay cámaras en el techo",
        "La terraza es pequeña",
      ],
      answer: "EL MOBILIARIO ES TRANSPARENTE",
      explanation: "Amanda lo entiende de golpe: casi no hay dónde ocultarse.",
    },
    {
      id: "l6",
      title: "Pulso ninja",
      prompt: "Encadena la maniobra exacta para desaparecer de la vista del guardia.",
      inputLabel: "Ejecuta el sigilo",
      mode: "memory",
      hint: "Pequeña, quieta, invisible y luego movimiento.",
      answerKind: "sequence",
      options: ["Jardineras", "Encogerse", "Esperar", "Guardia pasa", "Despacho"],
      answer: "JARDINERAS, ENCOGERSE, ESPERAR, GUARDIA PASA, DESPACHO",
      explanation: "La clave es esconderse, hacerse pequeña, esperar y moverse en el hueco justo.",
    },
    {
      id: "l7",
      title: "Puerta de leyenda",
      prompt: "Marca el logro exacto del último tramo guiado.",
      inputLabel: "Cierra la misión",
      mode: "signal",
      hint: "No huye ni encuentra una llave: entra.",
      answerKind: "single-choice",
      options: [
        "Entrar en la terraza del despacho de Irma Dagon",
        "Huir de la torre",
        "Encontrar la llave en el ascensor",
        "Apagar los drones",
      ],
      answer: "ENTRAR EN LA TERRAZA DEL DESPACHO DE IRMA DAGON",
      explanation: "Ese es el cierre perfecto del recorrido.",
    },
    {
      id: "l8",
      title: "Combo definitivo",
      prompt: "Une rescate, apoyo, ruta y entrada final en una sola corrida perfecta.",
      inputLabel: "Fusiona la jugada",
      mode: "route",
      hint: "La última ronda pide leer la misión completa como una sola línea.",
      answerKind: "sequence",
      options: ["Resbala", "Dron", "Esme", "Ruta", "Jardineras", "Despacho"],
      answer: "RESBALA, DRON, ESME, RUTA, JARDINERAS, DESPACHO",
      explanation: "La versión leyenda pide unir rescate, apoyo, guía y entrada final en una sola cadena.",
    },
  ],
};
