import { ChallengeCatalogItem, RoundDefinition } from "../../../shared/game";

export const rounds: RoundDefinition[] = [
  {
    id: "cap20-pista",
    chapterNumber: 20,
    chapterTitle: "El pasadizo helado",
    challengeType: "pista-relampago",
    minigameTitle: "Clave del pasadizo",
    teaser: "Encuentra la pista que advertía la trampa del panel.",
    storyText:
      "Amanda y Eric avanzan por un pasadizo con telarañas, puertas antiguas y una sala metálica con teclado numérico.",
    prompt: "¿Qué detalle les advirtió que una tercera contraseña podía activar una trampa peligrosa?",
    inputLabel: "Elige la pista correcta",
    answerKind: "single-choice",
    options: [
      "Los respiraderos junto al techo",
      "Las telarañas del pasillo",
      "La falta de batería del móvil",
      "La escalera de caracol",
    ],
    answer: "Los respiraderos junto al techo",
    explanation: "Eric detectó los respiraderos y dedujo que por allí podía salir gas u otra trampa.",
    timeLimitSec: 20,
  },
  {
    id: "cap20-memoria",
    chapterNumber: 20,
    chapterTitle: "El pasadizo helado",
    challengeType: "memoria-flash",
    minigameTitle: "Ruta de exploración",
    teaser: "Recuerda el orden del descenso por el túnel secreto.",
    storyText:
      "La exploración del pasadizo obliga a fijarse en las señales que aparecen antes de llegar al panel.",
    prompt: "Memoriza la ruta y escríbela en el mismo orden separada por comas.",
    inputLabel: "Secuencia de la ruta",
    answerKind: "text",
    answer: "TELARANAS, PUERTAS, ESCALERA, PANEL",
    explanation: "El recorrido clave fue telarañas, puertas, escalera y panel numérico.",
    timeLimitSec: 24,
    memorySequence: ["Telarañas", "Puertas", "Escalera", "Panel"],
    memoryRevealMs: 5000,
  },
  {
    id: "cap20-decision",
    chapterNumber: 20,
    chapterTitle: "El pasadizo helado",
    challengeType: "decision-secreta",
    minigameTitle: "Alarma roja",
    teaser: "Decide qué ocurrió al introducir la contraseña equivocada.",
    storyText:
      "Tras el tercer intento en el teclado, todo cambia de golpe dentro de la cámara metálica.",
    prompt: "¿Qué pasó justo después de pulsar ENTER con la contraseña equivocada?",
    inputLabel: "Elige la consecuencia inmediata",
    answerKind: "single-choice",
    options: [
      "Las luces se volvieron rojas y salió gas",
      "La puerta se abrió en silencio",
      "Benson apareció con una llave",
      "El panel se apagó por completo",
    ],
    answer: "Las luces se volvieron rojas y salió gas",
    explanation: "El fallo activó alarma, luces rojas intermitentes y gas descendiendo desde los respiraderos.",
    timeLimitSec: 20,
  },
  {
    id: "cap21-pista",
    chapterNumber: 21,
    chapterTitle: "Benson al rescate",
    challengeType: "pista-relampago",
    minigameTitle: "Rescate inesperado",
    teaser: "Reconoce quién interrumpió el caos en la sala.",
    storyText:
      "Cuando la alarma se detiene y el gas desaparece, una figura conocida se recorta en el umbral.",
    prompt: "¿Quién apareció para cortar el caos dentro de la cámara?",
    inputLabel: "Elige al rescatador",
    answerKind: "single-choice",
    options: ["Benson", "La tía Paula", "Esme", "Un vigilante"],
    answer: "Benson",
    explanation: "Benson fue quien apareció en la puerta y calmó a Amanda y Eric.",
    timeLimitSec: 18,
  },
  {
    id: "cap21-memoria",
    chapterNumber: 21,
    chapterTitle: "Benson al rescate",
    challengeType: "memoria-flash",
    minigameTitle: "Secuencia de calma",
    teaser: "Recuerda cómo se apagó la emergencia.",
    storyText:
      "El susto termina en una cadena rápida de cambios que devuelven la sala a la normalidad.",
    prompt: "Memoriza la secuencia y escríbela en el mismo orden separada por comas.",
    inputLabel: "Secuencia de normalización",
    answerKind: "text",
    answer: "LUZ AMARILLA, ALARMA, GAS, BENSON",
    explanation: "La sala recuperó luz amarilla, se apagó la alarma, el gas fue aspirado y apareció Benson.",
    timeLimitSec: 24,
    memorySequence: ["Luz amarilla", "Alarma", "Gas", "Benson"],
    memoryRevealMs: 5000,
  },
  {
    id: "cap21-decision",
    chapterNumber: 21,
    chapterTitle: "Benson al rescate",
    challengeType: "decision-secreta",
    minigameTitle: "Sin pánico",
    teaser: "Elige la lectura correcta de la escena del gas.",
    storyText:
      "Amanda cree que va a morir, pero Benson deja claro que la situación era distinta a lo que parecía.",
    prompt: "¿Qué idea transmite Benson sobre la sala de seguridad?",
    inputLabel: "Elige la interpretación correcta",
    answerKind: "single-choice",
    options: [
      "No era una sala mortal real, sino una protección de la mansión",
      "La llave estaba escondida dentro del gas",
      "Eric había activado la alarma a propósito",
      "La cámara pertenecía a Dagon Corp.",
    ],
    answer: "No era una sala mortal real, sino una protección de la mansión",
    explanation: "Benson le quita dramatismo: la sala protegía el acceso, no estaba diseñada para matarlos.",
    timeLimitSec: 20,
  },
  {
    id: "cap22-pista",
    chapterNumber: 22,
    chapterTitle: "Cena y confianza",
    challengeType: "pista-relampago",
    minigameTitle: "Cuenta atrás",
    teaser: "Ubica el peligro real que amenaza a la mansión.",
    storyText:
      "Durante la cena, la tía Paula revela la urgencia que pesa sobre la Mansión Black.",
    prompt: "¿Qué amenaza concreta compartió la tía Paula durante la cena?",
    inputLabel: "Elige la amenaza principal",
    answerKind: "single-choice",
    options: [
      "El banco puede quedarse con la mansión por impagos",
      "La galería se derrumbará esa noche",
      "Benson piensa abandonar a los Black",
      "La llave de diamante fue destruida",
    ],
    answer: "El banco puede quedarse con la mansión por impagos",
    explanation: "La urgencia del capítulo es económica: si no pagan pronto, perderán la mansión.",
    timeLimitSec: 20,
  },
  {
    id: "cap22-memoria",
    chapterNumber: 22,
    chapterTitle: "Cena y confianza",
    challengeType: "memoria-flash",
    minigameTitle: "Botones del ascensor",
    teaser: "Recuerda las marcas del ascensor secreto.",
    storyText:
      "Amanda descubre un ascensor oculto con tres botones clave que conectan distintas zonas de la mansión.",
    prompt: "Memoriza los botones y escríbelos en orden de abajo hacia arriba separados por comas.",
    inputLabel: "Orden de botones",
    answerKind: "text",
    answer: "T, PB, A",
    explanation: "Los botones del ascensor secreto eran T, PB y A.",
    timeLimitSec: 22,
    memorySequence: ["T", "PB", "A"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap22-decision",
    chapterNumber: 22,
    chapterTitle: "Cena y confianza",
    challengeType: "decision-secreta",
    minigameTitle: "Confianza total",
    teaser: "Decide qué exigió la tía Paula antes de hablar.",
    storyText:
      "Antes de contarle a Eric la verdad sobre la situación de la mansión, la tía Paula plantea una condición.",
    prompt: "¿Qué necesitó confirmar la tía Paula antes de hablar delante de Eric?",
    inputLabel: "Elige la condición",
    answerKind: "single-choice",
    options: [
      "Que Amanda confiaba en Eric",
      "Que Eric sabía abrir la galería",
      "Que Benson aprobaba el plan",
      "Que el banco había llamado esa tarde",
    ],
    answer: "Que Amanda confiaba en Eric",
    explanation: "La conversación siguió solo cuando Amanda afirmó que confiaba de verdad en Eric.",
    timeLimitSec: 20,
  },
  {
    id: "cap23-pista",
    chapterNumber: 23,
    chapterTitle: "El gran libro Black",
    challengeType: "pista-relampago",
    minigameTitle: "Origen secreto",
    teaser: "Identifica la raíz histórica del legado Black.",
    storyText:
      "Amanda y Eric leen la historia de los Black gracias a una traducción preparada por Benson.",
    prompt: "Según la traducción, ¿con qué civilización antigua arranca la historia de los Black?",
    inputLabel: "Elige el origen correcto",
    answerKind: "single-choice",
    options: ["Antiguo Egipto", "Roma", "Grecia", "Mesopotamia"],
    answer: "Antiguo Egipto",
    explanation: "El libro sitúa el origen del legado Black en el Antiguo Egipto.",
    timeLimitSec: 18,
  },
  {
    id: "cap23-memoria",
    chapterNumber: 23,
    chapterTitle: "El gran libro Black",
    challengeType: "memoria-flash",
    minigameTitle: "Misión del culto",
    teaser: "Recuerda los valores asociados a Maat.",
    storyText:
      "El libro explica que los Black protegían el equilibrio del mundo inspirados por la diosa Maat.",
    prompt: "Memoriza los valores y escríbelos en el mismo orden separados por comas.",
    inputLabel: "Valores de Maat",
    answerKind: "text",
    answer: "VERDAD, JUSTICIA, ARMONIA",
    explanation: "La traducción vincula a Maat con verdad, justicia y armonía cósmica.",
    timeLimitSec: 24,
    memorySequence: ["Verdad", "Justicia", "Armonía"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap23-decision",
    chapterNumber: 23,
    chapterTitle: "El gran libro Black",
    challengeType: "decision-secreta",
    minigameTitle: "La función Black",
    teaser: "Decide cuál era la labor central del legado.",
    storyText:
      "El legado de los Black no consiste en acumular tesoros, sino en evitar que ciertos artefactos dañen a la humanidad.",
    prompt: "¿Cuál era la misión principal de la familia Black según el libro?",
    inputLabel: "Elige la misión",
    answerKind: "single-choice",
    options: [
      "Retirar objetos peligrosos de circulación",
      "Vender reliquias a gobiernos secretos",
      "Construir mansiones en cada país",
      "Entrenar mayordomos invisibles",
    ],
    answer: "Retirar objetos peligrosos de circulación",
    explanation: "El culto Black escondía artefactos peligrosos para mantener el equilibrio entre bien y mal.",
    timeLimitSec: 20,
  },
  {
    id: "cap24-pista",
    chapterNumber: 24,
    chapterTitle: "La llave de diamante",
    challengeType: "pista-relampago",
    minigameTitle: "Pista maestra",
    teaser: "Encuentra la clave que abre la galería.",
    storyText:
      "Tras horas de lectura, Amanda y Eric encuentran por fin una pista clara sobre la llave que buscan.",
    prompt: "¿Qué llave abre la galería donde se guardan los artefactos?",
    inputLabel: "Elige la llave correcta",
    answerKind: "single-choice",
    options: [
      "La llave de diamante",
      "La llave de plata",
      "La llave de cristal rojo",
      "La llave del ático",
    ],
    answer: "La llave de diamante",
    explanation: "La pista encontrada confirma que la galería se abre con la llave de diamante.",
    timeLimitSec: 18,
  },
  {
    id: "cap24-memoria",
    chapterNumber: 24,
    chapterTitle: "La llave de diamante",
    challengeType: "memoria-flash",
    minigameTitle: "Diseño imposible",
    teaser: "Recuerda los detalles físicos de la llave.",
    storyText:
      "La traducción incluye un dibujo minucioso de la llave y varios detalles que pueden servir para reconocerla.",
    prompt: "Memoriza los rasgos y escríbelos en el mismo orden separados por comas.",
    inputLabel: "Rasgos de la llave",
    answerKind: "text",
    answer: "DIAMANTE, PLUMA, UNICA",
    explanation: "La llave parecía de diamante, tenía cabeza en forma de pluma y era imposible de duplicar.",
    timeLimitSec: 24,
    memorySequence: ["Diamante", "Pluma", "Única"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap24-decision",
    chapterNumber: 24,
    chapterTitle: "La llave de diamante",
    challengeType: "decision-secreta",
    minigameTitle: "Búsqueda digital",
    teaser: "Decide qué hizo Eric para tirar del hilo de la pista.",
    storyText:
      "Con la pista en la mano, Eric cambia de la lectura a la búsqueda tecnológica en el taller.",
    prompt: "¿Qué hizo Eric justo después de encontrar la referencia a la llave?",
    inputLabel: "Elige la siguiente acción",
    answerKind: "single-choice",
    options: [
      "Usó los ordenadores del taller para investigarla",
      "Llamó al banco para ganar tiempo",
      "Bajó al pasadizo con Benson",
      "Escondió el libro en el ático",
    ],
    answer: "Usó los ordenadores del taller para investigarla",
    explanation: "Eric aprovechó los ordenadores del taller para seguir la pista de la llave.",
    timeLimitSec: 20,
  },
  {
    id: "cap25-pista",
    chapterNumber: 25,
    chapterTitle: "Invitación inesperada",
    challengeType: "pista-relampago",
    minigameTitle: "Entrada perfecta",
    teaser: "Detecta la oportunidad que cambia el plan.",
    storyText:
      "Amanda y Eric buscan cómo infiltrarse en la Torre Dagon cuando aparece una opción mucho mejor.",
    prompt: "¿Qué oportunidad les abre una puerta real para entrar en Dagon Corp.?",
    inputLabel: "Elige la oportunidad",
    answerKind: "single-choice",
    options: [
      "La invitación de Esme a la fiesta de gala",
      "Un uniforme de seguridad olvidado",
      "Un plano escondido en clase",
      "Una llamada de Irma Dagon",
    ],
    answer: "La invitación de Esme a la fiesta de gala",
    explanation: "La invitación de Esme resuelve el problema de acceso a la recepción en Dagon Corp.",
    timeLimitSec: 20,
  },
  {
    id: "cap25-memoria",
    chapterNumber: 25,
    chapterTitle: "Invitación inesperada",
    challengeType: "memoria-flash",
    minigameTitle: "Plan de infiltración",
    teaser: "Recuerda ideas del almuerzo antes de la invitación.",
    storyText:
      "Antes de la ayuda de Esme, Amanda y Eric pasan el recreo evaluando formas absurdas y menos absurdas de colarse.",
    prompt: "Memoriza las ideas y escríbelas en el mismo orden separadas por comas.",
    inputLabel: "Ideas del recreo",
    answerKind: "text",
    answer: "ADULTOS, CAMAREROS, FIESTA",
    explanation: "Primero pensaron en hacerse pasar por adultos, luego por camareros, y finalmente llegó la fiesta.",
    timeLimitSec: 24,
    memorySequence: ["Adultos", "Camareros", "Fiesta"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap25-decision",
    chapterNumber: 25,
    chapterTitle: "Invitación inesperada",
    challengeType: "decision-secreta",
    minigameTitle: "Código social",
    teaser: "Elige qué exigía el evento de Dagon Corp.",
    storyText:
      "La fiesta a la que Esme los invita no es informal: todo el contexto obliga a adaptarse.",
    prompt: "¿Cómo era la fiesta a la que Esme invitó a Amanda y Eric?",
    inputLabel: "Elige la descripción",
    answerKind: "single-choice",
    options: [
      "Una fiesta de gala",
      "Una feria tecnológica escolar",
      "Un concierto benéfico",
      "Una cena familiar secreta",
    ],
    answer: "Una fiesta de gala",
    explanation: "Esme aclara que es un evento de gala y hasta ofrece ayudar con la ropa adecuada.",
    timeLimitSec: 18,
  },
  {
    id: "cap26-pista",
    chapterNumber: 26,
    chapterTitle: "La noche antes",
    challengeType: "pista-relampago",
    minigameTitle: "Lealtad en riesgo",
    teaser: "Ubica la razón emocional que mueve a Eric.",
    storyText:
      "La noche previa, Eric reflexiona sobre su amistad con Amanda y el peligro del golpe.",
    prompt: "¿Qué le importa más a Eric en este capítulo?",
    inputLabel: "Elige la motivación principal",
    answerKind: "single-choice",
    options: [
      "Que Amanda esté bien",
      "Conseguir fama en el instituto",
      "Ganarle a Benson en tecnología",
      "Evitar estudiar para el examen",
    ],
    answer: "Que Amanda esté bien",
    explanation: "Más allá de la aventura, Eric piensa sobre todo en proteger a Amanda.",
    timeLimitSec: 18,
  },
  {
    id: "cap26-memoria",
    chapterNumber: 26,
    chapterTitle: "La noche antes",
    challengeType: "memoria-flash",
    minigameTitle: "Mensajes de apoyo",
    teaser: "Recuerda el tono de la conversación nocturna.",
    storyText:
      "Eric termina escribiéndole a Amanda para animarla y medir sus nervios antes del golpe.",
    prompt: "Memoriza los temas del chat y escríbelos en el mismo orden separados por comas.",
    inputLabel: "Temas del chat",
    answerKind: "text",
    answer: "EXAMEN, SEGUIR, ESME",
    explanation: "Su conversación gira alrededor del examen, seguir adelante y la broma sobre Esme.",
    timeLimitSec: 24,
    memorySequence: ["Examen", "Seguir", "Esme"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap26-decision",
    chapterNumber: 26,
    chapterTitle: "La noche antes",
    challengeType: "decision-secreta",
    minigameTitle: "Chat estratégico",
    teaser: "Decide qué frase define mejor la respuesta de Eric.",
    storyText:
      "Amanda le pregunta si sigue dispuesto a continuar y Eric responde sin echarse atrás.",
    prompt: "¿Qué actitud muestra Eric cuando Amanda le pregunta si quiere seguir adelante?",
    inputLabel: "Elige la actitud",
    answerKind: "single-choice",
    options: [
      "Confirma que sí y la anima con humor",
      "Le pide posponerlo una semana",
      "Le dice que irá solo Benson",
      "Rompe el móvil para no pensarlo",
    ],
    answer: "Confirma que sí y la anima con humor",
    explanation: "Eric mantiene su compromiso y usa el humor para rebajar la tensión.",
    timeLimitSec: 18,
  },
  {
    id: "cap27-pista",
    chapterNumber: 27,
    chapterTitle: "Todo listo para el golpe",
    challengeType: "pista-relampago",
    minigameTitle: "Equipo especial",
    teaser: "Identifica la herramienta clave para guiar la misión.",
    storyText:
      "Antes del golpe, Benson reparte a Eric dispositivos y planes de apoyo desde el taller.",
    prompt: "¿Qué llevaba cargado el dispositivo transparente que recibió Eric?",
    inputLabel: "Elige la opción correcta",
    answerKind: "single-choice",
    options: [
      "Los planos de la Torre Dagon",
      "Las cuentas del banco",
      "La traducción del libro Black",
      "La lista de invitados completa",
    ],
    answer: "Los planos de la Torre Dagon",
    explanation: "El dispositivo plano incluía los planos para coordinar la infiltración.",
    timeLimitSec: 20,
  },
  {
    id: "cap27-memoria",
    chapterNumber: 27,
    chapterTitle: "Todo listo para el golpe",
    challengeType: "memoria-flash",
    minigameTitle: "Kit del operador",
    teaser: "Recuerda el equipo técnico que acompaña a Eric.",
    storyText:
      "La preparación del golpe combina tecnología, comunicación y apoyo remoto de Benson.",
    prompt: "Memoriza el equipo y escríbelo en el mismo orden separado por comas.",
    inputLabel: "Equipo de Eric",
    answerKind: "text",
    answer: "DISPOSITIVO, MANDO, GAFAS",
    explanation: "Eric recibe un dispositivo con planos, un mando y unas gafas de comunicación.",
    timeLimitSec: 24,
    memorySequence: ["Dispositivo", "Mando", "Gafas"],
    memoryRevealMs: 4500,
  },
  {
    id: "cap27-decision",
    chapterNumber: 27,
    chapterTitle: "Todo listo para el golpe",
    challengeType: "decision-secreta",
    minigameTitle: "Precaución extrema",
    teaser: "Decide qué descubre Amanda al entrar al evento.",
    storyText:
      "Cuando llegan a Dagon Corp., Amanda inspecciona rápido a quienes controlan la entrada.",
    prompt: "¿Qué detecta Amanda en los vigilantes de acceso?",
    inputLabel: "Elige la observación correcta",
    answerKind: "single-choice",
    options: [
      "Que iban armados",
      "Que eran hologramas",
      "Que estaban distraídos con un dron",
      "Que conocían a Eric del instituto",
    ],
    answer: "Que iban armados",
    explanation: "Amanda advierte el bulto de las armas bajo las chaquetas de los vigilantes.",
    timeLimitSec: 20,
  },
  {
    id: "cap28-pista",
    chapterNumber: 28,
    chapterTitle: "Drones al rescate",
    challengeType: "pista-relampago",
    minigameTitle: "Apoyo en el aire",
    teaser: "Reconoce quién salva a Amanda al borde de la caída.",
    storyText:
      "Amanda pierde apoyos mientras escala, pero una ayuda remota cambia la situación en el último momento.",
    prompt: "¿Qué la ayudó a no caer al vacío?",
    inputLabel: "Elige el salvavidas",
    answerKind: "single-choice",
    options: [
      "Un dron enviado por Benson",
      "Una cuerda lanzada por Eric",
      "Una cornisa secreta abierta por Esme",
      "Una ventana automática",
    ],
    answer: "Un dron enviado por Benson",
    explanation: "Benson ve el problema a distancia y envía drones para darle apoyo y estabilidad.",
    timeLimitSec: 18,
  },
  {
    id: "cap28-memoria",
    chapterNumber: 28,
    chapterTitle: "Drones al rescate",
    challengeType: "memoria-flash",
    minigameTitle: "Cadena de rescate",
    teaser: "Recuerda cómo se recompone la escalada.",
    storyText:
      "La escena de rescate ocurre en una secuencia vertiginosa que combina apoyo tecnológico y sangre fría.",
    prompt: "Memoriza la secuencia y escríbela en el mismo orden separada por comas.",
    inputLabel: "Secuencia de rescate",
    answerKind: "text",
    answer: "DRON, APOYO, RECUPERARSE, SUBIR",
    explanation: "El dron llega, da apoyo, Amanda recupera el equilibrio y continúa subiendo.",
    timeLimitSec: 24,
    memorySequence: ["Dron", "Apoyo", "Recuperarse", "Subir"],
    memoryRevealMs: 5000,
  },
  {
    id: "cap28-decision",
    chapterNumber: 28,
    chapterTitle: "Drones al rescate",
    challengeType: "decision-secreta",
    minigameTitle: "Última esperanza",
    teaser: "Decide a quién acude Eric cuando se corta la comunicación.",
    storyText:
      "Con Amanda en plena escalada y el enlace roto, Eric necesita otra persona para salvar la misión.",
    prompt: "¿A quién decide contarle la verdad Eric para intentar llegar al piso cincuenta a tiempo?",
    inputLabel: "Elige a la aliada",
    answerKind: "single-choice",
    options: ["Esme", "La tía Paula", "Irma Dagon", "Benson"],
    answer: "Esme",
    explanation: "Eric confía en Esme como último recurso cuando todo se complica.",
    timeLimitSec: 18,
  },
  {
    id: "cap29-pista",
    chapterNumber: 29,
    chapterTitle: "La terraza final",
    challengeType: "pista-relampago",
    minigameTitle: "Escondite de cristal",
    teaser: "Ubica el único escondite útil de la terraza.",
    storyText:
      "Amanda llega a la terraza del despacho de Irma Dagon y necesita esconderse antes de que la vea un guardia.",
    prompt: "¿Dónde consiguió esconderse Amanda en la terraza?",
    inputLabel: "Elige el escondite",
    answerKind: "single-choice",
    options: ["Tras unas jardineras", "Debajo de una mesa de cristal", "Dentro del ascensor", "En una fuente"],
    answer: "Tras unas jardineras",
    explanation: "El mobiliario era transparente, así que las jardineras eran la única cobertura útil.",
    timeLimitSec: 18,
  },
  {
    id: "cap29-memoria",
    chapterNumber: 29,
    chapterTitle: "La terraza final",
    challengeType: "memoria-flash",
    minigameTitle: "Ruta guiada",
    teaser: "Recuerda las instrucciones de Eric para llegar arriba.",
    storyText:
      "Eric retoma la comunicación y guía a Amanda por los últimos metros de la infiltración.",
    prompt: "Memoriza la ruta y escríbela en el mismo orden separada por comas.",
    inputLabel: "Ruta final",
    answerKind: "text",
    answer: "IZQUIERDA, SUBIR, TERRAZA, JARDINERAS",
    explanation: "Eric la manda a la izquierda, luego a subir, alcanzar la terraza y cubrirse en las jardineras.",
    timeLimitSec: 24,
    memorySequence: ["Izquierda", "Subir", "Terraza", "Jardineras"],
    memoryRevealMs: 5000,
  },
  {
    id: "cap29-decision",
    chapterNumber: 29,
    chapterTitle: "La terraza final",
    challengeType: "decision-secreta",
    minigameTitle: "Frialdad total",
    teaser: "Decide qué debía hacer Amanda para salir con vida.",
    storyText:
      "Antes de entrar al despacho, Amanda entiende que el pánico sería el peor enemigo.",
    prompt: "¿Qué necesitaba hacer Amanda para superar la situación en la terraza?",
    inputLabel: "Elige la mejor decisión",
    answerKind: "single-choice",
    options: [
      "Pensar con frialdad y usar las opciones a su alrededor",
      "Romper la cristalera y correr",
      "Esperar quieta a que el guardia se fuera solo",
      "Llamar a la tía Paula desde la terraza",
    ],
    answer: "Pensar con frialdad y usar las opciones a su alrededor",
    explanation: "El capítulo insiste en que solo manteniendo la calma podía cumplir la misión y salir viva.",
    timeLimitSec: 20,
  },
];

export const challengeCatalog: ChallengeCatalogItem[] = rounds.map(
  ({ id, chapterNumber, chapterTitle, challengeType, minigameTitle, teaser }) => ({
    id,
    chapterNumber,
    chapterTitle,
    challengeType,
    minigameTitle,
    teaser,
  }),
);

